spring:
  application:
    name: pin-manager

  datasource:
    url: jdbc:postgresql://localhost:5432/otpDB
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
        jdbc:
          lob:
            non_contextual_creation: true

server:
  port: 8084
